name: zipCollection

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: zipCollection
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mount DMG and aar it
        run:  chmod +x mount.sh && bash mount.sh
      - name: Upload Application
        uses: actions/upload-artifact@v3
        with:
          name: zipCollection Output
          path: |
              /tmp/output.aar
